#!/usr/bin/env python3
"""Map an API delta onto the doc pages it invalidates, and emit a work order.

Consumes the output of ``diff-api.py`` and searches the docs for every affected
symbol, producing one work order per Diataxis type. The orchestrator hands each
work order to the matching editor subagent; nothing else needs to read the docs.

Two rules are enforced here rather than left to an agent's judgment, because
both are mechanical facts and getting either wrong silently destroys work:

1. **Notebooks are the source; their .mdx siblings are generated.**
   ``src/content/docs/oss/checks/{quickstart,how-to,tutorials,use-cases}/*.mdx``
   are git-ignored build output regenerated by ``make regen-mdx``. Editing one
   produces a diff that evaporates. If a sibling ``<stem>.ipynb`` exists, the
   edit target is the notebook -- always.

2. **A page's Diataxis type determines who edits it and how aggressively.**
   See references/edit-policy.md.

Usage:
    python scripts/triage-docs.py delta.json --docs src/content/docs -o work-order.json
"""

from __future__ import annotations

import argparse
import json
import re
import sys
from pathlib import Path
from typing import Any

# Diataxis type per directory. Anything outside these is "other": still reported,
# but no editor owns it -- it needs a human. (oss/solutions/ and the top-level
# oss/*.md pages fall here, and they DO reference the API.)
DIATAXIS_BY_DIR = {
    "tutorials": "tutorial",
    "how-to": "how-to",
    "use-cases": "how-to",
    "reference": "reference",
    "explanation": "explanation",
}

# Pages that sit outside a Diataxis directory but are not "other". Matched on the
# path tail, and checked before DIATAXIS_BY_DIR. quickstart.ipynb is the case that
# forced this: it lives at checks/quickstart.ipynb rather than
# checks/tutorials/quickstart.ipynb, so directory typing alone orphans the single
# highest-traffic page in the tree -- it drew 11 deltas on one refresh and no
# editor was allowed to touch it.
DIATAXIS_BY_PATH = {
    "checks/quickstart.ipynb": "tutorial",
}

SEARCHABLE_SUFFIXES = {".md", ".mdx", ".ipynb"}


def diataxis_type(path: Path) -> str:
    posix = path.as_posix()
    for suffix, kind in DIATAXIS_BY_PATH.items():
        if posix.endswith(suffix):
            return kind
    for part in path.parts:
        if part in DIATAXIS_BY_DIR:
            return DIATAXIS_BY_DIR[part]
    return "other"


def edit_target(path: Path) -> Path:
    """Resolve a hit to the file that should actually be edited.

    A generated .mdx is redirected to the .ipynb it was built from. Hand-written
    .mdx (reference/, explanation/, and the index.mdx landing pages that live
    inside notebook directories) have no sibling notebook and are returned as-is.
    """
    if path.suffix == ".mdx":
        notebook = path.with_suffix(".ipynb")
        if notebook.exists():
            return notebook
    return path


def search_notebook(path: Path, pattern: re.Pattern[str]) -> list[dict[str, Any]]:
    """Search a notebook's cell sources, reporting cell indices rather than lines.

    nbformat stores each cell's source as a list of strings; joining them is what
    lets a pattern match across the lines of a single cell.
    """
    try:
        notebook = json.loads(path.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError):
        return []

    hits: list[dict[str, Any]] = []
    for index, cell in enumerate(notebook.get("cells", [])):
        source = cell.get("source", [])
        text = "".join(source) if isinstance(source, list) else str(source)
        if pattern.search(text):
            hits.append({"cell": index, "cell_type": cell.get("cell_type", "code")})
    return hits


def search_text(path: Path, pattern: re.Pattern[str]) -> list[dict[str, Any]]:
    try:
        lines = path.read_text(encoding="utf-8").splitlines()
    except OSError:
        return []
    return [{"line": n} for n, line in enumerate(lines, 1) if pattern.search(line)]


# Receivers that are never a giskard object, for member names common enough to
# collide. ``asyncio.run(`` is the one that actually bit: Suite.run, Scenario.run,
# ScenarioRunner.run and Check.run all changed signature in a single release, so
# every page showing the standard ``asyncio.run(main())`` idiom collected four
# error-severity deltas and was dispatched to an editor that had nothing to do.
FOREIGN_RECEIVERS = {
    "run": ("asyncio", "unittest", "subprocess"),
}


def symbol_pattern(symbol: str, member_of: str | None) -> re.Pattern[str]:
    """Build the search pattern for one symbol.

    Top-level symbols are imported and then used bare (``from giskard.checks
    import Suite`` ... ``Suite(...)``), so the leaf name as a whole word is right.

    Class members must NOT be searched that way. ``Check.run`` would search for
    the bare word "run", which matches ordinary English prose on 310 pages. A
    member is only meaningful as an attribute access, so anchor it on the dot.

    Anchoring on the dot is necessary but not sufficient: ``asyncio.run(`` is an
    attribute access too. For leaf names listed in FOREIGN_RECEIVERS, also reject
    the receivers that are definitely not ours -- ``scenario.run()`` still matches,
    ``asyncio.run()`` no longer does.
    """
    leaf = symbol.split(".")[-1]
    if member_of:
        foreign = FOREIGN_RECEIVERS.get(leaf)
        if foreign:
            # Python's re needs a fixed-width lookbehind and these receivers are
            # different lengths, so match the receiver explicitly and rule it out
            # with a lookahead instead.
            alternation = "|".join(re.escape(name) for name in foreign)
            return re.compile(
                rf"(?:(?<![\w.])(?!(?:{alternation})\.)[\w\]\)]+)"
                rf"\.{re.escape(leaf)}\s*[\(\[=,)\s]"
            )
        return re.compile(rf"\.{re.escape(leaf)}\s*[\(\[=,)\s]")
    return re.compile(rf"\b{re.escape(leaf)}\b")


def triage(delta: dict[str, Any], docs_root: Path) -> dict[str, Any]:
    pages = [
        p
        for p in sorted(docs_root.rglob("*"))
        if p.is_file() and p.suffix in SEARCHABLE_SUFFIXES
    ]

    # target path -> {diataxis, deltas: [...]}
    work: dict[str, dict[str, Any]] = {}
    undocumented: list[dict[str, Any]] = []

    for item in delta["deltas"]:
        pattern = symbol_pattern(item["symbol"], item.get("member_of"))
        matched_any = False

        for page in pages:
            hits = (
                search_notebook(page, pattern)
                if page.suffix == ".ipynb"
                else search_text(page, pattern)
            )
            if not hits:
                continue

            target = edit_target(page)
            # A hit in a generated .mdx and a hit in its .ipynb source collapse to
            # one task on the notebook; record that the mdx was where we saw it.
            key = target.as_posix()
            entry = work.setdefault(
                key,
                {"path": key, "diataxis": diataxis_type(target), "generated_from_hit": [], "deltas": []},
            )
            if target != page:
                shadow = page.as_posix()
                if shadow not in entry["generated_from_hit"]:
                    entry["generated_from_hit"].append(shadow)

            if not any(d["symbol"] == item["symbol"] and d["kind"] == item["kind"] for d in entry["deltas"]):
                entry["deltas"].append(
                    {
                        "kind": item["kind"],
                        "symbol": item["symbol"],
                        "severity": item["severity"],
                        "old_signature": item.get("old_signature"),
                        "new_signature": item.get("new_signature") or item.get("signature"),
                        "defaults": item.get("defaults"),
                        "hits": hits[:20],
                    }
                )
            matched_any = True

        # A new symbol nobody mentions is a feature with no docs. Report it; do
        # not invent a page for it. That is an editorial decision for a human.
        if not matched_any and item["kind"] == "symbol_added":
            undocumented.append(
                {
                    "symbol": item["symbol"],
                    "signature": item.get("signature", ""),
                    "doc_summary": item.get("doc_summary", ""),
                }
            )

    by_type: dict[str, list[dict[str, Any]]] = {}
    for entry in work.values():
        by_type.setdefault(entry["diataxis"], []).append(entry)
    for entries in by_type.values():
        entries.sort(key=lambda e: e["path"])

    errors = sum(
        1 for e in work.values() for d in e["deltas"] if d["severity"] == "error"
    )

    return {
        "from_version": delta.get("from_version"),
        "to_version": delta.get("to_version"),
        "to_ref": delta.get("to_ref"),
        "summary": {
            "pages_affected": len(work),
            "pages_by_type": {k: len(v) for k, v in sorted(by_type.items())},
            "error_deltas_on_pages": errors,
            "undocumented_new_symbols": len(undocumented),
        },
        "work_by_type": dict(sorted(by_type.items())),
        "undocumented": sorted(undocumented, key=lambda u: u["symbol"]),
    }


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("delta", help="Delta JSON from diff-api.py")
    # Default to the OSS tree only. Pointing this at all of src/content/docs
    # drags in hub/, a different product whose pages mention names like "Suite"
    # and "Scenario" without ever using giskard.checks.
    parser.add_argument(
        "--docs", default="src/content/docs/oss", help="Docs subtree to triage"
    )
    parser.add_argument("-o", "--output", help="Write work order here instead of stdout")
    args = parser.parse_args()

    try:
        with open(args.delta, encoding="utf-8") as fh:
            delta = json.load(fh)
    except (OSError, json.JSONDecodeError) as exc:
        print(f"error: {exc}", file=sys.stderr)
        return 2

    docs_root = Path(args.docs)
    if not docs_root.is_dir():
        print(f"error: docs root not found: {docs_root}", file=sys.stderr)
        return 2

    order = triage(delta, docs_root)
    text = json.dumps(order, indent=2, sort_keys=True, ensure_ascii=False) + "\n"

    if args.output:
        with open(args.output, "w", encoding="utf-8") as fh:
            fh.write(text)
    else:
        sys.stdout.write(text)

    summary = order["summary"]
    print(
        f"{summary['pages_affected']} pages affected "
        f"{summary['pages_by_type']}; "
        f"{summary['error_deltas_on_pages']} error-severity; "
        f"{summary['undocumented_new_symbols']} undocumented new symbols",
        file=sys.stderr,
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
